# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [1]:
#a)
2.0 + (3.0/5.0)

2.6

In [2]:
#b)
(2.6 + 10.2) - 5.0 * 2.0

2.799999999999999

In [3]:
#c)
(2.6 / 2.799999999999999) + 33.8

34.72857142857143

In [4]:
#d)
2.6 / (2.79 + 34.72857142857143)

0.06929901382172639

In [5]:
#e)
0.06929901382172639 * 2

0.13859802764345278

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [6]:
#a)
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
lista_a

[2.0, 3.0, 5.0, 10, 20, 30]

In [7]:
#b)
lista_b = lista_a * 2
lista_b

[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

In [8]:
#c)
lista_c = lista_a + lista_b
print(lista_c)

[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]


In [9]:
#d)
lista_a = [2.0, 3.0, 5.0]
lista_b = [10, 20, 30]
lista_c = [2.0, 3.0, 5.0, 10, 20, 30]

In [10]:
lista_a / [lista_b * lista_c]

TypeError: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [11]:
lista_3 = [2.6, 2.80, 34.73, 0.07, 0.14]

In [12]:
lista3_raizqd = [x**0.5 for x in lista_3]
lista3_raizqd

[1.61245154965971,
 1.6733200530681511,
 5.8932164392630275,
 0.2645751311064591,
 0.37416573867739417]

In [13]:
lista3_conct = lista_3 + lista3_raizqd
lista3_conct

[2.6,
 2.8,
 34.73,
 0.07,
 0.14,
 1.61245154965971,
 1.6733200530681511,
 5.8932164392630275,
 0.2645751311064591,
 0.37416573867739417]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [14]:
import numpy as np

In [15]:
lista_dup = lista3_conct * 2

In [16]:
array = np.array(lista_dup)
array

array([ 2.6       ,  2.8       , 34.73      ,  0.07      ,  0.14      ,
        1.61245155,  1.67332005,  5.89321644,  0.26457513,  0.37416574,
        2.6       ,  2.8       , 34.73      ,  0.07      ,  0.14      ,
        1.61245155,  1.67332005,  5.89321644,  0.26457513,  0.37416574])

In [17]:
array_2 = array.reshape(5, 4)
array_2

array([[ 2.6       ,  2.8       , 34.73      ,  0.07      ],
       [ 0.14      ,  1.61245155,  1.67332005,  5.89321644],
       [ 0.26457513,  0.37416574,  2.6       ,  2.8       ],
       [34.73      ,  0.07      ,  0.14      ,  1.61245155],
       [ 1.67332005,  5.89321644,  0.26457513,  0.37416574]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [18]:
medias = array_2.mean(axis=0).tolist()
print(medias)

[7.881579036834921, 2.149966745520026, 7.881579036834923, 2.149966745520026]


## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [19]:
array_2.shape

(5, 4)

In [20]:
array_3 = np.append(array_2, [array_2.mean(axis=0)], axis=0)
print(array_3)

[[ 2.6         2.8        34.73        0.07      ]
 [ 0.14        1.61245155  1.67332005  5.89321644]
 [ 0.26457513  0.37416574  2.6         2.8       ]
 [34.73        0.07        0.14        1.61245155]
 [ 1.67332005  5.89321644  0.26457513  0.37416574]
 [ 7.88157904  2.14996675  7.88157904  2.14996675]]


## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [21]:
import pandas as pd

In [30]:
array_4 = array_3.reshape(-1, 4)
array_4

array([[ 2.6       ,  2.8       , 34.73      ,  0.07      ],
       [ 0.14      ,  1.61245155,  1.67332005,  5.89321644],
       [ 0.26457513,  0.37416574,  2.6       ,  2.8       ],
       [34.73      ,  0.07      ,  0.14      ,  1.61245155],
       [ 1.67332005,  5.89321644,  0.26457513,  0.37416574],
       [ 7.88157904,  2.14996675,  7.88157904,  2.14996675]])

In [31]:
df = pd.DataFrame(array_4).round(3)
print(df)

        0      1       2      3
0   2.600  2.800  34.730  0.070
1   0.140  1.612   1.673  5.893
2   0.265  0.374   2.600  2.800
3  34.730  0.070   0.140  1.612
4   1.673  5.893   0.265  0.374
5   7.882  2.150   7.882  2.150


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [33]:
df = df.iloc [:]
print(df)

        0      1       2      3
0   2.600  2.800  34.730  0.070
1   0.140  1.612   1.673  5.893
2   0.265  0.374   2.600  2.800
3  34.730  0.070   0.140  1.612
4   1.673  5.893   0.265  0.374
5   7.882  2.150   7.882  2.150


In [34]:
df["media"] = df.mean(axis=1)
print(df)

        0      1       2      3     media
0   2.600  2.800  34.730  0.070  10.05000
1   0.140  1.612   1.673  5.893   2.32950
2   0.265  0.374   2.600  2.800   1.50975
3  34.730  0.070   0.140  1.612   9.13800
4   1.673  5.893   0.265  0.374   2.05125
5   7.882  2.150   7.882  2.150   5.01600


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [35]:
df.describe()

,0,1,2,3,media
count,6.000000,6.000000,6.000000,6.000000,6.000000
mean,7.881667,2.149833,7.881667,2.149833,5.015750
std,13.455286,2.107253,13.455286,2.107253,3.758533
min,0.140000,0.070000,0.140000,0.070000,1.509750
25%,0.617000,0.683500,0.617000,0.683500,2.120812
50%,2.136500,1.881000,2.136500,1.881000,3.672750
75%,6.561500,2.637500,6.561500,2.637500,8.107500
max,34.730000,5.893000,34.730000,5.893000,10.050000


## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [37]:
df.columns = ["col1", "col2", "col3", "col4", "medias"]
df.index = ["linha1", "linha2", "linha3", "linha4", "linha5", "medias"]
df

,col1,col2,col3,col4,medias
linha1,2.600,2.800,34.730,0.070,10.05000
linha2,0.140,1.612,1.673,5.893,2.32950
linha3,0.265,0.374,2.600,2.800,1.50975
linha4,34.730,0.070,0.140,1.612,9.13800
linha5,1.673,5.893,0.265,0.374,2.05125
medias,7.882,2.150,7.882,2.150,5.01600


In [39]:
df.to_csv("df.csv")