# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [37]:
a = 2.0 + (3.0 / 5.0) == 10
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
c = 10 <= a/b + 33.8 <100
d = 5 != a / (b + c)
e = 33 == d*2

In [38]:
print(a)
print(b)
print(c)
print(d)
print(e)

False
True
True
True
False


## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [1]:
('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)

True

In [2]:
['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)

False

In [3]:
['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]

True

In [4]:
['a',1,True,'b',0,False] < ['a',True,1]

False

In [7]:
['a',1,True,'b',0,False] != 1

True

In [11]:
['a',True,1] <= ['a',True,1] > ['a',1,True,'b',0,False]

False

## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [12]:
import pandas as pd

In [36]:
df_3 = pd.read_csv("df.csv", index_col = "Unnamed: 0").round(3)
df_3

,col1,col2,col3,col4,medias
linha1,2.600,2.800,34.730,0.070,10.050
linha2,0.140,1.612,1.673,5.893,2.330
linha3,0.265,0.374,2.600,2.800,1.510
linha4,34.730,0.070,0.140,1.612,9.138
linha5,1.673,5.893,0.265,0.374,2.051
medias,7.882,2.150,7.882,2.150,5.016


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [16]:
import numpy as np

In [21]:
array_int_uns = np.ones(df_3.shape)
array_int_uns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [22]:
df_3.values == array_int_uns

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [27]:
#R: Nenhum resultado da DataFrame é igual aos valores do array.

## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [23]:
df_3.values > array_int_uns

array([[ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False, False,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [28]:
#R: 22 valores da DataFrame são maiores que os valores do array.

## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [24]:
df_3.values <= array_int_uns

array([[False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False,  True,  True, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

In [29]:
#R: 8 valores da DataFrame são menores ou iguais aos valores do array.

## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [25]:
(df_3.values > 0) & (df_3.values < 1)

array([[False, False, False,  True, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False],
       [False,  True,  True, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

In [30]:
#R: 8 valores da DataFrame estão entre 0 e 1.

## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [31]:
df_3["medias"]

linha1    10.050
linha2     2.330
linha3     1.510
linha4     9.138
linha5     2.051
medias     5.016
Name: medias, dtype: float64

In [33]:
df_3["medias"] <= 5

linha1    False
linha2     True
linha3     True
linha4    False
linha5     True
medias    False
Name: medias, dtype: bool

In [34]:
#R: 3 valores são menores ou iguais a 5.

## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [32]:
df_3["medias"] > 5

linha1     True
linha2    False
linha3    False
linha4     True
linha5    False
medias     True
Name: medias, dtype: bool

In [35]:
#R:  3 valores são maiores que 5.