In [1]:
num_1 = 4
num_2 = 2
print(num_1 + num_2)
print(num_1 - num_2)

6
2


In [7]:
tupla_1 = (1,2,3)
tupla_2 = (1,2,3)
print(tupla_1 == tupla_2)

True


In [8]:
tupla_1 += tupla_2
display(tupla_1)
display(tupla_2)

(1, 2, 3, 1, 2, 3)

(1, 2, 3)

In [ ]:
#list() transforma em lista
list(tupla_1)

[1, 2, 3, 1, 2, 3]

In [24]:
lista_tupla_1 += tupla_1
lista_tupla_1

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [17]:
#indexação de lista 
lista_tupla_1[2]
#+= serve como um append, que fica somando valores

3

In [20]:
dict_1 = {"a": 1, "b":2, "c":30}
dict_2 = {"a":1, "b": 20}

In [ ]:
#não dá pra somar dicionarios pq ele é indexado manualmente, não tem ordem fixa

dict_1 + dict_2

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [22]:
# .update vai juntando os valores dos dois dicts
dict_1.update(dict_2)
dict_1

{'a': 1, 'b': 20, 'c': 30}

In [23]:
import numpy as np

In [26]:
array = np.array([lista_tupla_1])
array

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [ ]:
# assim faz a soma de 2 a cada elemento do array
array += 2
array

array([[7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [ ]:
# assim faz a multiplicação de 2 a cada elemento do array
array += array
array

array([[14, 16, 18, 14, 16, 18, 14, 16, 18, 14, 16, 18, 14, 16, 18, 14,
        16, 18]])

In [ ]:
# .insert coloca um valor em uma posição específica do array
np.insert(arr=array, obj=2, values=100) 

array([ 14,  16, 100,  18,  14,  16,  18,  14,  16,  18,  14,  16,  18,
        14,  16,  18,  14,  16,  18])

In [33]:
lista_tupla_1[2] = 100
lista_tupla_1

[1, 2, 100, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [37]:
# reshape muda a forma do array, nesse caso, ele tem 6 elementos, e eu quero que ele tenha 3 linhas e 2 colunas
array = np.array(lista_tupla_1).reshape(6,-1)
array

array([[  1,   2, 100],
       [  1,   2,   3],
       [  1,   2,   3],
       [  1,   2,   3],
       [  1,   2,   3],
       [  1,   2,   3]])

In [38]:
import pandas as pd

In [39]:
df = pd.DataFrame(array)
df

,0,1,2
0,1,2,100
1,1,2,3
2,1,2,3
3,1,2,3
4,1,2,3
5,1,2,3


In [41]:
# para somar 2 a cada elemento do dataframe, basta usar o operador +=
df += 2
df

,0,1,2
0,5,6,104
1,5,6,7
2,5,6,7
3,5,6,7
4,5,6,7
5,5,6,7


In [42]:
array_ones = np.ones_like(df)
array_ones[1,1] = 100
array_ones

array([[  1,   1,   1],
       [  1, 100,   1],
       [  1,   1,   1],
       [  1,   1,   1],
       [  1,   1,   1],
       [  1,   1,   1]])

In [44]:
df += array_ones
df

,0,1,2
0,7,8,106
1,7,206,9
2,7,8,9
3,7,8,9
4,7,8,9
5,7,8,9


In [45]:
# .values transforma o dataframe em um array
# .ones_like cria um array de uns com a mesma forma do dataframe
# .zeros_like cria um array de zeros com a mesma forma do dataframe

In [48]:
# OPERADORES RELACIONAIS
print("Py" == "Py")
print("Py" != "Py")

True
False


In [49]:
2 >= 2.0

True

In [52]:
2 <= 2.1

True

In [53]:
import numpy as np
import pandas as pd

In [54]:
(1,2)==(1.0,2.0)

True

In [ ]:
# classes diferentes dá False
(1,2)==[1,2]

False

In [77]:
np.random.seed(42)
array_1 = np.random.normal(0, 1, 1_000).reshape(-1, 10)
array_2 = np.random.normal(0, 1, 1_000).reshape(-1, 10)
print(array_1[:1])
print(array_2[:1])

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
   1.57921282  0.76743473 -0.46947439  0.54256004]]
[[ 1.39935544  0.92463368  0.05963037 -0.64693678  0.69822331  0.39348539
   0.89519322  0.6351718   1.04955272 -0.53523521]]


In [80]:
display(pd.DataFrame(array_1))
display(pd.DataFrame(array_2))

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040
...,...,...,...,...,...,...,...,...,...,...
95,-0.241236,0.352055,-1.251539,1.443765,-0.082151,1.117296,0.342725,0.456753,0.569767,0.447709
96,0.642723,1.329153,0.196521,0.709004,-0.089736,1.440117,-0.676392,1.800940,-0.040158,-1.430775
97,0.128104,-0.681052,0.840644,-0.652624,-0.446183,-1.889541,-0.452306,-2.423879,-1.583903,0.760415
98,0.785800,0.425458,-0.966976,-0.047711,-0.003603,-1.158365,1.503398,0.877362,-0.220964,0.026886


,0,1,2,3,4,5,6,7,8,9
0,1.399355,0.924634,0.059630,-0.646937,0.698223,0.393485,0.895193,0.635172,1.049553,-0.535235
1,1.317394,0.197600,2.075261,-0.689188,1.735964,0.197911,-0.651418,-0.483886,-0.320347,0.424166
2,0.522835,-0.573700,-0.024355,2.142270,1.727543,0.436324,0.038003,0.120031,0.613518,-1.022793
3,-0.257377,-1.668584,0.399223,0.647196,-0.483186,1.573987,-1.225766,-1.464375,0.224452,1.047098
4,1.683928,-0.458884,1.078681,-0.038508,-0.172627,0.883660,0.652323,-1.576392,1.476540,1.380091
...,...,...,...,...,...,...,...,...,...,...
95,-1.773032,1.261922,-0.905732,-0.653766,-0.595661,1.374438,-2.135674,3.137749,1.056057,0.223239
96,-0.054894,0.285554,0.521122,0.645216,0.555604,0.089581,-0.197338,-0.151273,-0.194908,1.133770
97,0.593557,-2.940389,0.655901,0.194736,-0.018709,-0.388518,1.124113,0.947526,-0.772878,0.407052
98,-0.971657,-1.379618,-0.626717,0.862393,0.953125,0.513085,0.725096,0.516178,-0.641482,0.431923


In [81]:
pd.DataFrame(array_1) <= pd.DataFrame(array_2)

,0,1,2,3,4,5,6,7,8,9
0,True,True,False,False,True,True,False,False,True,False
1,True,True,True,True,True,True,True,False,True,True
2,False,False,False,True,True,True,True,False,True,False
3,True,False,True,True,False,True,False,True,True,True
4,True,False,True,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...
95,False,True,True,False,False,True,False,True,True,False
96,False,False,True,False,True,False,True,False,False,True
97,True,False,False,True,True,True,True,True,True,False
98,False,False,True,True,True,True,False,False,False,True


In [82]:
df_1 = pd.DataFrame(array_1)
df_2 = pd.DataFrame(array_2)
df_1.head()

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040
